export const Filter = 'filter'
export const EventCategoryFilter = 'eventCategoryFilter'
export const ShowEventStreamFinishedEvents = 'showEventStreamFinishedEvents'
export const ShowInputEvents = 'showInputEvents'
export const ShowResponsePartEvents = 'showResponsePartEvents'
export const UseDevtoolsLayout = 'useDevtoolsLayout'
export const SelectedEventIndex = 'selectedEventIndex'
export const CloseDetails = 'closeDetails'
export const DetailTab = 'detailTab'
export const TimelineStartSeconds = 'timelineStartSeconds'
export const TimelineEndSeconds = 'timelineEndSeconds'
export const TimelineRangePreset = 'timelineRangePreset'
export const Refresh = 'refresh'

export const All = 'all'
export const Tools = 'tools'
export const Network = 'network'
export const Ui = 'ui'
export const Stream = 'stream'

export const Response = 'response'
export const Preview = 'preview'
export const Payload = 'payload'
export const Timing = 'timing'
