export const Filter = 'filter'
export const ShowEventStreamFinishedEvents = 'showEventStreamFinishedEvents'
export const ShowFullOutput = 'showFullOutput'
export const ShowInputEvents = 'showInputEvents'
export const ShowResponsePartEvents = 'showResponsePartEvents'
