export const Filter = 'filter'
export const EventCategoryFilter = 'eventCategoryFilter'
export const ShowEventStreamFinishedEvents = 'showEventStreamFinishedEvents'
export const ShowInputEvents = 'showInputEvents'
export const ShowResponsePartEvents = 'showResponsePartEvents'
export const UseDevtoolsLayout = 'useDevtoolsLayout'
export const SelectedEventIndex = 'selectedEventIndex'
export const CloseDetails = 'closeDetails'
